name: Official SonarQube Scan
description: >
  Scan your code with SonarQube to detect Bugs, Vulnerabilities and Code Smells in up to 27 programming languages!
branding:
  icon: check
  color: green
runs:
  using: docker
  image: Dockerfile
  network: ${{ inputs.net }}
  entrypoint: "/entrypoint.sh"
  post-entrypoint: "/cleanup.sh"

inputs:
  net:
    description: Net for docker container
    required: false
    default: bridge
  args:
    description: Additional arguments to the sonar-scanner
    required: false
  projectBaseDir:
    description: Set the sonar.projectBaseDir analysis property
    required: false
    default: .
